### ISSUE TITLE
Question about augmentation

### ISSUE THREAD

**Issue by tunglm2203** [facebookresearch/deep_bisim4control#10]
Hi. Thanks for sharing your work.

Could I ask did you use augmentation in your method? Since I didn't find any implemented transformation in your implementation.
But in the appendix, you mentioned:
> We modify the Soft Actor-Critic PyTorch implementation by Yarats and Kostrikov [33] and **augment** with a shared encoder between the actor and critic.

Am I understanding wrong?

Thank you in advance.

**Comment by amyzhang** [comment]
Hi!

We do not use data augmentation in our method. The word **augment** was used here to mean that we modified the original implementation with a convolutional encoder that is shared between the actor and critic, to adapt SAC to the pixel setting.
