### ISSUE TITLE
Hyper-paramters for OpenAi's classic control environments 

### ISSUE THREAD

**Issue by bheijden** [facebookresearch/deep_bisim4control#4]
Hi,

Great that you shared the code of your paper. I found the paper very interesting, and I wish to use it as a benchmark in my own work. However, I am struggling to even find a set of hyper-parameters that can solve the pendulum swing-up of the OpenAI's classic control suite using pixel images. 

What hyper-parameters configuration would you expect to work (for DBC and deepMDP)? The default ones do not seem to work out-of-the-box.  Below, I have listed the settings I use now. It would be great if you could give me some suggestions on which parameters to set/tune, so that I have a proper comparison with my own work.

Also, I had the following questions:

1. it was not entirely clear to me what transition model to choose ('deterministic', 'probabilistic', 'ensemble')? The ensemble method is only mentioned in future work, so probably not used in the implementation of the paper?

2. You specify a decoder_type for deepMDP, but i thought deepMDP did not require a decoder as it does not reconstruct observations, similar to DBC? If it does, the default is set to 'pixel' so that is probably it?

agent | bisim | deepMDP
-- | -- | --
action_repeat | 2 | 2
frame_stack | 3 | 3
batch_size | 128 | 128
hidden_dim |50 mentioned in Appendix C of paper, or use default of 256? | 50 mentioned in Appendix C of paper, or use default of 256?
bisim_coef | 0.5 | -
**Critic** |   |  
critic_lr | 1e-3 | 1e-3
critic_beta | 0.9 | 0.9
critic_tau | 0.005 | 0.005
critic_target_update_freq | 2 | 2
**Actor** |   |  
actor_lr | 1e-3 | 1e-3
actor_beta | 0.9 | 0.9
actor_log_std_min | -5 | -5
actor_log_std_max | 2 | 2
actor_target_update_freq | 2 | 2
**Encoder/Decoder** |   |  
encoder_type | pixel | pixel
encoder_feature_dim | 50 (or is this the hidden encoder dim mentioned in Appendix C of paper?) | 50 (or is this the hidden encoder dim mentioned in Appendix C of paper?) 
encoder_lr | 1e-3 | 1e-3
encoder_tau | 5e-3 | 5e-3
encoder_stride | 1 | 1
decoder_type | - | pixel???
decoder_lr | - | 1e-3
decoder_update_freq | - | 1
num_layers | 4 | 4
num_filters | 32 | 32
**SAC** |   |  
discount | 0.99 | 0.99
init_temperature | 0.01 | 0.01
alpha_lr | 1e-3 | 1e-3
alpha_beta | 0.9 | 0.9
**Transition model** |   |  
transition_model_type | deterministic | deterministic

**Comment by amyzhang** [comment]
Hi, the hyerparameters used for DM control are in `run_local.sh`. DeepMDP has a decoder option because they required a decoder to get it working on Atari in their paper, our runs did not use the decoder so you can set it to "identity". Hope that helps!

**Comment by bheijden** [comment]
What a speedy response, thanks!
