### ISSUE TITLE
Reproducing the Generalization Experiments

### ISSUE THREAD

**Issue by rraileanu** [facebookresearch/deep_bisim4control#5]
Hi! 

I would like to reproduce the distractor and natural video environments used in the generalization experiments in Section 6.2 (as well as perhaps the results themselves). What are the commands for creating and training on these environments? It seems like one needs to specify args.total_frames as well as a directory with videos to replace the standard backgrounds (i.e. the args.resource_files). Could you specify how to generate these videos or add a download link?

Thank you!

**Comment by amyzhang** [comment]
Hi! 

Apologies for the late reply. The hyperparameters to try are the ones in the scripts, you can try `run_local.sh`. You can download the videos from here: https://deepmind.com/research/open-source/kinetics 
It is the Kinetics 400 dataset, and we used the 'car_driving' train set. I will add a download link. You can just pass the directory you save those videos to to `--resource_files`
