### ISSUE TITLE
Cannot reproduce paper's results

### ISSUE THREAD

**Issue by noobitard** [facebookresearch/deep_bisim4control#8]
Hi. Thanks for your paper. I'm really interested in it!

I'm trying to reproduce the paper's results on the Walker Walk with natural background. However, currently I can't reproduce the reported result. I ran the code with the parameters specified in the run_local.sh file:

```
#!/bin/bash

DOMAIN=walker
TASK=walk

SAVEDIR=./log

CUDA_VISIBLE_DEVICES=1 python train.py \
    --domain_name ${DOMAIN} \
    --task_name ${TASK} \
    --agent 'bisim' \
    --init_steps 1000 \
    --num_train_steps 1000000 \
    --encoder_type pixel \
    --decoder_type pixel \
    --img_source video \
    --resource_files '/mnt/tungnd13/dreamer/videos/train/*.mp4' \
    --transition_model_type 'probabilistic' \
    --action_repeat 2 \
    --critic_tau 0.01 \
    --encoder_tau 0.05 \
    --decoder_weight_lambda 0.0000001 \
    --hidden_dim 1024 \
    --total_frames 1000 \
    --num_layers 4 \
    --num_filters 32 \
    --batch_size 128 \
    --init_temperature 0.1 \
    --alpha_lr 1e-4 \
    --alpha_beta 0.5 \
    --work_dir ${SAVEDIR}/${DOMAIN}_${TASK} \
    --seed 1 $@
```
However, after around 100k steps, the return is still <100. The paper reported results is around 200 mean return after 100k.

I also have some more questions. 

1. Did you use different videos for each episode or use the same video for every training episode? The code seems to use only one video, right? Correct me if i'm wrong :)
2. Did you use test dataset for eval env (by setting `eval_resource_files` to the test path instead of train)?

Thanks!

**Comment by amyzhang** [comment]
Hi! I'm really sorry you're having this issue :/ I just tried re-running the local.sh script and am getting
`| eval | S: 100000 | ER: 331.7788
| train | E: 201 | S: 100500 | D: 116.7 s | R: 393.3435 | BR: 0.3757 | ALOSS: -24.9345 | CLOSS: 4.0074 | RLOS
S: 0.0000 | MR: 0.0000`

but you do have to specify the `eval_resource_files` to the same directory as training (I did not use the test path for evaluation), apologies for that not being in the script, fixing that now. And with 1000 frames it should be "reusing" the same 1000 frames for each episode since each episode is 1000 steps. But the code is randomly grabbing a video from that directory, and appending another if the first is <1000 frames. Hope that helps!

**Comment by noobitard** [comment]
Thanks for your reply. However, I still cannot get a high return on natural walker walk. My bash file is now:

```
#!/bin/bash

DOMAIN=walker
TASK=walk

SAVEDIR=./log

CUDA_VISIBLE_DEVICES=1 python train.py \
    --domain_name ${DOMAIN} \
    --task_name ${TASK} \
    --agent 'bisim' \
    --init_steps 1000 \
    --num_train_steps 1000000 \
    --encoder_type pixel \
    --decoder_type pixel \
    --img_source video \
    --resource_files '../bisim/video/*.mp4' \
    --eval_resource_files '../bisim/video/*.mp4' \
    --transition_model_type 'probabilistic' \
    --action_repeat 2 \
    --critic_tau 0.01 \
    --encoder_tau 0.05 \
    --decoder_weight_lambda 0.0000001 \
    --hidden_dim 1024 \
    --total_frames 1000 \
    --num_layers 4 \
    --num_filters 32 \
    --batch_size 128 \
    --init_temperature 0.1 \
    --alpha_lr 1e-4 \
    --alpha_beta 0.5 \
    --work_dir ${SAVEDIR}/${DOMAIN}_${TASK} \
    --seed 1 $@ \
    --save_tb
```

Here's the tensorboard:
![image](https://user-images.githubusercontent.com/26506960/102475059-f9c4fb00-408b-11eb-9055-e60bec6910bf.png)

It's kinda weird... I didn't modify the code, except removing the carla import from the train.py file.

**Comment by amyzhang** [comment]
Got it. Will try to repro your issues next week!

**Comment by noobitard** [comment]
Hello, do you have any updates regarding my problem? Thanks

**Comment by amyzhang** [comment]
Hi, yes I noticed some discrepancies in my running scripts. I was able to repro a poor result with the dynamics model set to probabilistic. You should be able to reproduce the results in the paper by setting the dynamics to "ensemble". Keep me posted on how that works! I just ran with 3 seeds to check and it does seem higher variance/a bit slower to improve than the original figure, but final performance should be close enough:
![image](https://user-images.githubusercontent.com/6619016/103023424-cad2dd00-4502-11eb-8fa5-a893fdbf89ae.png)
